stages:
  - test
  - release
  - deploy
  - migrate

variables:
  REGISTRY: "gcr.io/positive-apex-225210/marketmanager"
  POSTGRES_DB: marketmanager
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  DB_DATABASE: marketmanager
  DB_USERNAME: runner
  DB_PASSWORD: ""
  DB_HOSTNAME: postgres
  STAGING_HOSTNAME: 35.240.84.184
  GCP_CONTEXT: gke_positive-apex-225210_europe-west1-c_main
  SECRET_KEY: "testing_key"
  PY_ENV: staging
  MARKET_MANAGER_DAEMON_HOST: localhost
  MARKET_MANAGER_DAEMON_PORT: 5000
  COIN_MANAGER_URL: "http://localhost"
  POD_IP: localhost
  REDIS_HOST: localhost
  DEBUG: "True"
  ALLOWED_HOSTS: "localhost"
  CORS_ORIGIN_WHITELIST: "http://localhost"
  SECURE_SSL_REDIRECT: "True"
  INFLUXDB_ORG: wholefolio
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_DEFAULT_BUCKET: marketmanager

unittests:
  stage: test
  variables:
    DOCKER_INFLUXDB_INIT_USERNAME: influxdb
    DOCKER_INFLUXDB_INIT_PASSWORD: influxdb
    DOCKER_INFLUXDB_INIT_ORG: wholefolio
    DOCKER_INFLUXDB_INIT_PASSWORD: marketmanager
  tags:
   - docker
  image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
  before_script:
    - apk add jq
    - wget https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.6-linux-amd64.tar.gz
    - tar xzvf influxdb2-2.0.6-linux-amd64.tar.gz
    - influxdb2-2.0.6-linux-amd64/influx setup -f --host ${INFLUXDB_URL} -u ${DOCKER_INFLUXDB_INIT_USERNAME} -p ${DOCKER_INFLUXDB_INIT_PASSWORD} -o ${INFLUXDB_ORG} -b ${INFLUXDB_DEFAULT_BUCKET}
    - export INFLUXDB_TOKEN=$(influxdb2-2.0.6-linux-amd64/influx auth list --json | jq .[].token | sed "s/\"//g")
  script:
    - python3 manage.py test --noinput
  services:
    - postgres:latest
    - influxdb:2.0.6

linter:
  stage: test
  tags:
    - docker
  image: registry.gitlab.com/cryptohunters/base-images/flake8:latest
  script:
    - flake8 --exclude="*migrations*,manage.py" --max-line-length=110

integration-tests:
  services:
    - postgres:latest
    - influxdb:2.0.6
  variables:
    DOCKER_INFLUXDB_INIT_USERNAME: influxdb
    DOCKER_INFLUXDB_INIT_PASSWORD: influxdb
    DOCKER_INFLUXDB_INIT_ORG: wholefolio
    DOCKER_INFLUXDB_INIT_BUCKET: marketmanager
    DOCKER_INFLUXDB_INIT_MODE: setup
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "JCIvUyHIwmyq1u8VxkPWKW4tgEuIXXkZsSlUMZ7c9dJG8nSWqKmopxv-w450EzjajpEuLPJjknD_52CTCcRb_g=="
    INFLUXDB_TOKEN: "JCIvUyHIwmyq1u8VxkPWKW4tgEuIXXkZsSlUMZ7c9dJG8nSWqKmopxv-w450EzjajpEuLPJjknD_52CTCcRb_g=="
  stage: test
  tags:
    - docker
  image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
  script:
    # Enable one exchange and verify the fetch_exchange_data task comples
    - python3 manage.py migrate
    - python3 manage.py add_exchange --name binance
    - python3 manage.py fetch_exchange_data 1

release-image:
    stage: release
    script:
      - docker build -t $REGISTRY:latest .
      - docker tag $REGISTRY:latest $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:latest

deploy-internal:
   stage: deploy
   script:
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-daemon marketmanager-daemon=$REGISTRY:${CI_PIPELINE_ID}
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-api marketmanager-api=$REGISTRY:${CI_PIPELINE_ID}
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-celery marketmanager-celery=$REGISTRY:${CI_PIPELINE_ID}

db:migrate-staging:
   stage: migrate
   image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
   tags:
     - docker
   variables:
     PY_ENV: "staging"
     DB_HOSTNAME: "$STAGING_DB_HOST"
     DB_USERNAME: "$GCP_DB_USERNAME"
     DB_PASSWORD: "$GCP_DB_PASSWORD"
     MARKET_MANAGER_DAEMON_PORT: 5000
   when: manual
   script:
      - python3 manage.py migrate
