stages:
  - build
  - test
  - release
  - deploy
  - migrate

variables:
  REGISTRY: "wholefolio/marketmanager"
  POSTGRES_DB: marketmanager
  POSTGRES_USER: user
  POSTGRES_PASSWORD: user
  POSTGRES_HOST_AUTH_METHOD: trust
  GCP_CONTEXT: gke_positive-apex-225210_europe-west1-c_main
  DOCKER_INFLUXDB_INIT_USERNAME: influxdb
  DOCKER_INFLUXDB_INIT_PASSWORD: influxdb
  DOCKER_INFLUXDB_INIT_ORG: wholefolio
  DOCKER_INFLUXDB_INIT_PASSWORD: marketmanager
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "JCIvUyHIwmyq1u8VxkPWKW4tgEuIXXkZsSlUMZ7c9dJG8nSWqKmopxv-w450EzjajpEuLPJjknD_52CTCcRb_g=="
  DOCKER_INFLUXDB_INIT_BUCKET: marketmanager
  INFLUXDB_TOKEN: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN

build-image:
    stage: build
    script:
      - docker login -u $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
      - docker build -t $REGISTRY:test .
      - docker push $REGISTRY:test

unittests:
  stage: test
  services:
  - postgres:latest
  - influxdb:2.0.6
  tags:
   - docker
  image: $REGISTRY:test
  script:
    - source .env
    - source `find /root/.local/share/virtualenvs/ -name activate`
    - sleep 120
    - python3 manage.py test --noinput

linter:
  stage: test
  tags:
    - docker
  image: $REGISTRY:test
  script:
    - pip3 install flake8 && flake8 --exclude="*migrations*,manage.py" --max-line-length=110

integration-tests:
  stage: test
  services:
    - postgres:latest
    - influxdb:2.0.6
  tags:
    - docker
  image: $REGISTRY:test
  variables:
    ENABLED_EXCHANGES: binance,bittrex
  script:
    - source .env
    - source `find /root/.local/share/virtualenvs/ -name activate`
    - python3 manage.py migrate
    - python3 manage.py integration_tests

release-image:
    stage: release
    script:
      - docker login -u $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
      - docker pull $REGISTRY:test
      - docker tag $REGISTRY:test $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:latest

deploy-internal:
   stage: deploy
   script:
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-daemon marketmanager-daemon=$REGISTRY:${CI_PIPELINE_ID}
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-api marketmanager-api=$REGISTRY:${CI_PIPELINE_ID}
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-celery marketmanager-celery=$REGISTRY:${CI_PIPELINE_ID}

db:migrate:
   stage: migrate
   image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
   tags:
     - docker
   variables:
     PY_ENV: "staging"
     DB_HOSTNAME: "$STAGING_DB_HOST"
     DB_USERNAME: "$GCP_DB_USERNAME"
     DB_PASSWORD: "$GCP_DB_PASSWORD"
   when: manual
   script:
      - pipenv run python3 manage.py migrate
