stages:
  - test
  - release
  - deploy
  - migrate

services:
  - postgres:latest

variables:
  REGISTRY: "gcr.io/positive-apex-225210/marketmanager"
  POSTGRES_DB: marketmanager
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  DB_DATABASE: marketmanager
  DB_USERNAME: runner
  DB_PASSWORD: ""
  DB_HOSTNAME: postgres
  STAGING_HOSTNAME: 35.240.84.184
  GCP_CONTEXT: gke_positive-apex-225210_europe-west1-c_main
  SECRET_KEY: "testing_key"
  PY_ENV: staging
  MARKET_MANAGER_DAEMON_HOST: localhost
  MARKET_MANAGER_DAEMON_PORT: 5000
  POD_IP: localhost
  REDIS_HOST: localhost
  DEBUG: "True"

unittests:
  stage: test
  tags:
   - docker
  image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
  script:
    - python3 manage.py test --noinput

usability-tests:
  stage: test
  tags:
    - docker
  image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
  script:
    # Enable one exchange and verify the fetch_exchange_data task comples
    - python3 manage.py migrate
    - python3 manage.py add_exchange --name binance
    - python3 manage.py fetch_exchange_data 1

release-image:
    stage: release
    script:
      - docker build -t $REGISTRY:latest .
      - docker tag $REGISTRY:latest $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:latest

deploy-internal:
   stage: deploy
   script:
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-daemon marketmanager-daemon=$REGISTRY:${CI_PIPELINE_ID}
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-api marketmanager-api=$REGISTRY:${CI_PIPELINE_ID}
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-celery marketmanager-celery=$REGISTRY:${CI_PIPELINE_ID}

db:migrate-staging:
   stage: migrate
   image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
   tags:
     - docker
   variables:
     PY_ENV: "staging"
     DB_HOSTNAME: "$STAGING_DB_HOST"
     DB_USERNAME: "$GCP_DB_USERNAME"
     DB_PASSWORD: "$GCP_DB_PASSWORD"
     MARKET_MANAGER_DAEMON_PORT: 5000
   when: manual
   script:
      - python3 manage.py migrate
