stages:
  - test
  - release
  - deploy
  - migrate

variables:
  REGISTRY: "gcr.io/production-185413/marketmanager"
  DB_DATABASE: marketmanager
  DB_USERNAME: marketmanager
  DB_PASSWORD: marketmanager
  DB_HOSTNAME: 192.168.13.187
  STAGING_HOSTNAME: 35.225.253.18
  GCP_CONTEXT: gke_production-185413_us-central1-a_crypto-test
  SECRET_KEY: "testing_key"
  PY_ENV: staging


unittests:
  stage: test
  tags:
   - docker
  variables:
    PY_ENV: dev
  image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
  script:
    - python3 manage.py test

release-image:
    stage: release
    script:
      - docker build --build-arg SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY}" -t $REGISTRY:latest .
      - docker tag $REGISTRY:latest $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:latest

deploy-internal:
   stage: deploy
   script:
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-daemon marketmanager-daemon=$REGISTRY:${CI_PIPELINE_ID}
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-api marketmanager-api=$REGISTRY:${CI_PIPELINE_ID}

db:migrate-staging:
   stage: migrate
   before_script: []
   image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
   variables:
     DB_HOSTNAME: "$STAGING_DB_HOST"
     DB_USERNAME: "$GCP_DB_USERNAME"
     DB_PASSWORD: "$GCP_DB_PASSWORD"
   when: manual
   script:
      - python3 manage.py migrate
