stages:
  - test
  - release
  - deploy
  - migrate

variables:
  REGISTRY: "gcr.io/positive-apex-225210/marketmanager"
  POSTGRES_DB: marketmanager
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  DB_DATABASE: $POSTGRES_DB
  DB_USERNAME: $POSTGRES_USER
  DB_PASSWORD: $POSTGRES_PASSWORD
  DB_HOSTNAME: postgres
  GCP_CONTEXT: gke_positive-apex-225210_europe-west1-c_main
  DOCKER_INFLUXDB_INIT_USERNAME: influxdb
  DOCKER_INFLUXDB_INIT_PASSWORD: influxdb
  DOCKER_INFLUXDB_INIT_ORG: wholefolio
  DOCKER_INFLUXDB_INIT_PASSWORD: marketmanager
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "JCIvUyHIwmyq1u8VxkPWKW4tgEuIXXkZsSlUMZ7c9dJG8nSWqKmopxv-w450EzjajpEuLPJjknD_52CTCcRb_g=="
  INFLUXDB_TOKEN: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN

unittests:
  stage: test
  services:
  - postgres:latest
  - influxdb:2.0.6
  tags:
   - docker
  image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
  script:
    - source .env
    - python3 manage.py test --noinput

linter:
  stage: test
  tags:
    - docker
  image: registry.gitlab.com/cryptohunters/base-images/flake8:latest
  script:
    - flake8 --exclude="*migrations*,manage.py" --max-line-length=110

integration-tests:
  stage: test
  services:
    - postgres:latest
    - influxdb:2.0.6
  tags:
    - docker
  image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
  variables:
    ENABLED_EXCHANGES: binance,bittrex
  script:
    - source .env
    - python3 manage.py migrate
    - python3 manage.py integration_tests

release-image:
    stage: release
    script:
      - docker build -t $REGISTRY:latest .
      - docker tag $REGISTRY:latest $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:${CI_PIPELINE_ID}
      - docker push $REGISTRY:latest

deploy-internal:
   stage: deploy
   script:
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-daemon marketmanager-daemon=$REGISTRY:${CI_PIPELINE_ID}
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-api marketmanager-api=$REGISTRY:${CI_PIPELINE_ID}
      - kubectl --context=$GCP_CONTEXT set image deployment/marketmanager-celery marketmanager-celery=$REGISTRY:${CI_PIPELINE_ID}

db:migrate:
   stage: migrate
   image: registry.gitlab.com/cryptohunters/base-images/marketmanager:latest
   tags:
     - docker
   variables:
     PY_ENV: "staging"
     DB_HOSTNAME: "$STAGING_DB_HOST"
     DB_USERNAME: "$GCP_DB_USERNAME"
     DB_PASSWORD: "$GCP_DB_PASSWORD"
     MARKET_MANAGER_DAEMON_PORT: 5000
   when: manual
   script:
      - python3 manage.py migrate
