# Generated by Django 2.0.7 on 2018-08-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('storage_exchange_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('interval', models.IntegerField()),
            ],
            options={
                'db_table': 'exchanges',
            },
        ),
        migrations.CreateModel(
            name='ExchangeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(null=True)),
                ('last_run_id', models.CharField(max_length=256, null=True)),
                ('last_run_status', models.TextField(null=True)),
                ('time_started', models.DateTimeField(null=True)),
                ('running', models.BooleanField(default=False)),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Exchange')),
            ],
            options={
                'db_table': 'exchange_status',
            },
        ),
    ]
