# Generated by Django 2.1 on 2018-09-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180827_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('base', models.CharField(max_length=10)),
                ('quote', models.CharField(max_length=10)),
                ('volume', models.FloatField(null=True)),
                ('last', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Exchange')),
            ],
            options={
                'db_table': 'markets',
            },
        ),
    ]
