# Generated by Django 2.1 on 2018-09-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_market'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('name', 'exchange')},
        ),
    ]
