# Generated by Django 2.1 on 2018-09-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180908_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='quote',
            field=models.CharField(max_length=25),
        ),
    ]
