# Generated by Django 2.1 on 2018-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180913_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='base',
            field=models.CharField(max_length=20),
        ),
    ]
