# Generated by Django 2.1.3 on 2018-12-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181024_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='api_url',
            field=models.URLField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='url',
            field=models.URLField(max_length=128, null=True),
        ),
    ]
