# Generated by Django 3.0 on 2020-01-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_exchangestatus_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='fiat_markets',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
