# Generated by Django 3.0.7 on 2020-07-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_exchange_fiat_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
