# Generated by Django 2.2 on 2021-09-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210614_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='market',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='market',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='market',
            name='open',
            field=models.FloatField(default=0),
        ),
    ]
