# Generated by Django 2.2 on 2021-12-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211116_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyFiatPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=64, unique=True)),
                ('price', models.FloatField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Exchange')),
            ],
            options={
                'db_table': 'currency_fiat_prices',
                'unique_together': {('currency', 'exchange')},
            },
        ),
    ]
