apiVersion: v1
kind: Service
metadata:
  labels:
    app: marketmanager-daemon
  name: marketmanager-daemon
  namespace: marketmanager
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: marketmanager-daemon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketmanager-daemon
  namespace: marketmanager
  labels:
    app: marketmanager-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketmanager-daemon
  template:
    metadata:
      labels:
        app: marketmanager-daemon
    spec:
      containers:
      - name: marketmanager-daemon
        image: wholefolio/marketmanager:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["pipenv run python3 manage.py daemon start"]
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 200Mi
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: marketmanager
