---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: marketmanager
  labels:
    run: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    run: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: marketmanager
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 3
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
